title = "PagePP - Static Site Generator"
name = "PagePP"
description = "A suckless static site generator"
url = "https://thestaccato.github.io"
baseurl = "/pagepp"
locale = "en-US"

[social]
email = "none@example.org"
googlescholar = "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
orcid = "https://orcid.org"
github = "thestaccato/pagepp"
gitlab = "gitlab.com"
git = "https://git.org"
codeberg = "codeberg.org"
forgejo = "https://git.kernal.org"
matrix = "https://matrix.org"
linkedin = "yourlinkedin"
bluesky = "bsky.app"
mastodon = "https://mastodon.social/@yourusername"
sourcehut = "https://sr.ht"
fediverse = "https://your-fediverse-instance/@you"
kofi = "https://ko-fi.com/yourusername"
