title = "Your name / site title"
name = "Your Name"
description = "Your Name's portfolio"
url = "https://thestaccato.github.io"
baseurl = "/pagepp"
locale = "en-US"

[author]
name = "Your Name"
bio = "Short biography"
email = "none@example.org"
# googlescholar = "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
orcid = "https://orcid.org"
# pubmed = "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
github = "thestaccato/pagepp"
# gitlab = "gitlab.com"
# git = "https://git.org"
# codeberg = "codeberg.org"
# forgejo = "https://git.kernal.org"
matrix = "https://matrix.org"
# linkedin = "yourlinkedin"
# twitter = "yourtwitter"
# bluesky = "bsky.app"
# mastodon = "https://mastodon.social/@yourusername"
# youtube = "@yourchannel"
sourcehut = "https://sr.ht"
